config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#top'
  get 'thankyou', to: 'statipages#show'
  get 'sushi', to: 'sushis#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sushi.rb
class Sushi < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def top; end
end

app/controllers/sushis_controller.rb
class SushisController < ApplicationController
  before_action :set_sushi, only: [:show]

  def show; end

  private

  def set_sushi
    @sushi = Sushi.order("RANDOM()").first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/sushi_helper.rb
module SushiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>寿司るーれっと</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/staticpages/top.html.erb
<div class= 'container'>
  <div class = 'child'>
    <%= image_tag 'nigirizushi_moriawase.png', width: '200', height: '200' %>
    <br>
    <h1>寿司るーれっと</h1>
    <br>
    <div>
      <%= link_to '回してみる', sushi_path, class: "btn" %>
    </div>
  </div>
</div>

app/views/sushis/show.html.erb
<div class = 'container'>
  <div class = 'child'>
    <% if @sushi.present? %>
      <h2><%= @sushi.name %></h2>
        <%= image_tag "#{@sushi.sushi_image}.png", width: '200', height: '200'  %>
      <div>
      <br>
        <%= @sushi.comment%>
      </div>
      <br><br>
      <div>
        <%= link_to sushi_path do %>
          <%= image_tag 'mottotaberu.png' %>
        <% end %>
        <%= link_to "https://twitter.com/intent/tweet?text=#{@sushi.name} にしようかな！｜寿司るーれっと &url=https://sushi-roulette.onrender.com" do %>
          <%= image_tag 'sharesuru.png' %>
        <% end %>
      </div>
    <% else %>
      <h2>寿司情報が見つかりません</h2>
    <% end %>
  </div>
</div>